name: Periodic health check

on:
  #schedule:
  #  - cron: '15/15 * * * *'
  push:
    branches:
      - main

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check health of application
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-part11-pokedex-delicate-snow-9474.fly.dev/health